# change file name to "compose.yml" in order to use
# command: mv compose_example.yml compose.yml

services:
  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    hostname: freshrss
    restart: unless-stopped
    environment:
      TZ: Etc/UTC
#      CRON_MIN: "25,55" # updates every 25th minute and the 55th minute of every hour
    volumes:
      - ./data:/var/www/FreshRSS/data
      - ./extensions:/var/www/FreshRSS/extensions
    logging:
      options:
        max-size: 10m

  nginx:
    image: nginx:alpine
    container_name: nginx-freshrss
    restart: unless-stopped
    depends_on:
      - freshrss
    ports:
      - "5015:5015"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - /docker/tailscale-certs:/etc/nginx/certs:ro # absolute path
    read_only: true
    tmpfs:
      - /var/cache/nginx
      - /var/run
      - /var/tmp
