# change file name to "compose.yml" in order to use
# command: mv compose_example.yml compose.yml

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    command: --interval 21600 watchtower brave tailscale-brave app-flame tailscale-flame mumble-web nginx-mumbleweb freshrss tailscale-freshrss app-ntfy tailscale-ntfy hbbs hbbr vaultwarden nginx-vaultwarden jellyfin tailscale-jellyfin jellyseerr mariadb_jellyseerr tailscale-jellyseerr gluetun transmission mullvad-browser audiobookshelf tailscale-audiobookshelf app-dockge tailscale-dockge
    # Whitelist: Actively update only these containers & Check every 6 hours
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=America/New_York

      # Logging
      - WATCHTOWER_LOG_LEVEL=info

      # Email Notifications
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=redacted@gmx.com
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=redacted@proton.me
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=mail.gmx.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=redacted@gmx.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=redacted_password
      - WATCHTOWER_NOTIFICATION_EMAIL_SUBJECTTAG=docker-up

      - DOCKER_API_VERSION=1.44

    restart: always
