services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    environment:
      TZ: America/New_York
      FTLCONF_webserver_api_password: 'REPLACE_WITH_YOUR_PASSWORD'
      FTLCONF_dns_upstreams: 127.0.0.1#5053
      FTLCONF_dns_listeningMode: all
      FTLCONF_dns_hosts: |-
        192.168.68.2 omv.time-puffin.ts.net
        192.168.68.2 flame.time-puffin.ts.net
        192.168.68.2 freshrss.time-puffin.ts.net
        192.168.68.2 jellyfin.time-puffin.ts.net
        192.168.68.2 jellyseerr.time-puffin.ts.net
        192.168.68.2 brave.time-puffin.ts.net
        192.168.68.2 audiobookshelf.time-puffin.ts.net
        192.168.68.2 ntfy.time-puffin.ts.net
        192.168.68.2 obico.time-puffin.ts.net
        192.168.68.2 immich.time-puffin.ts.net
        192.168.68.2 vaultwarden.time-puffin.ts.net
        192.168.68.2 mullvad.time-puffin.ts.net
        192.168.68.2 transmission.time-puffin.ts.net
        192.168.68.2 dockge.time-puffin.ts.net
        192.168.68.2 owncast.time-puffin.ts.net

        2600:1700:2920:1760:aa5e:45ff:fecf:3c47 omv.time-puffin.ts.net
        2600:1700:2920:1760:aa5e:45ff:fecf:3c47 flame.time-puffin.ts.net
        2600:1700:2920:1760:aa5e:45ff:fecf:3c47 freshrss.time-puffin.ts.net
        2600:1700:2920:1760:aa5e:45ff:fecf:3c47 jellyfin.time-puffin.ts.net
        2600:1700:2920:1760:aa5e:45ff:fecf:3c47 jellyseerr.time-puffin.ts.net
        2600:1700:2920:1760:aa5e:45ff:fecf:3c47 brave.time-puffin.ts.net
        2600:1700:2920:1760:aa5e:45ff:fecf:3c47 audiobookshelf.time-puffin.ts.net
        2600:1700:2920:1760:aa5e:45ff:fecf:3c47 ntfy.time-puffin.ts.net
        2600:1700:2920:1760:aa5e:45ff:fecf:3c47 obico.time-puffin.ts.net
        2600:1700:2920:1760:aa5e:45ff:fecf:3c47 immich.time-puffin.ts.net
        2600:1700:2920:1760:aa5e:45ff:fecf:3c47 vaultwarden.time-puffin.ts.net
        2600:1700:2920:1760:aa5e:45ff:fecf:3c47 mullvad.time-puffin.ts.net
        2600:1700:2920:1760:aa5e:45ff:fecf:3c47 transmission.time-puffin.ts.net
        2600:1700:2920:1760:aa5e:45ff:fecf:3c47 dockge.time-puffin.ts.net
        2600:1700:2920:1760:aa5e:45ff:fecf:3c47 owncast.time-puffin.ts.net

        192.168.68.118 qidi.time-puffin.ts.net
        192.168.68.86 k1.time-puffin.ts.net
      PIHOLE_UID: "1000"
      PIHOLE_GID: "1000"
    ports:
      - "192.168.68.2:53:53/tcp"
      - "192.168.68.2:53:53/udp"
      - "[2600:1700:2920:1760:aa5e:45ff:fecf:3c47]:53:53/tcp"
      - "[2600:1700:2920:1760:aa5e:45ff:fecf:3c47]:53:53/udp"
      - "8088:80/tcp"
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped

  dnsproxy:
    image: adguard/dnsproxy:latest
    container_name: dnsproxy-quad9
    network_mode: "service:pihole"
    command:
      - "--listen=127.0.0.1"
      - "--port=5053"

      # Upstream DNS:
      - "--upstream=https://dns.quad9.net/dns-query"
      # - "--upstream=https://dns.nextdns.io/REDACTED_ID"

      # Bootstrap DNS used to resolve DoH upstream hostnames.
      - "--bootstrap=9.9.9.9:53"
      - "--bootstrap=149.112.112.112:53"
      - "--bootstrap=2620:fe::fe:53"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx-pihole
    depends_on:
      - pihole
    ports:
      - "192.168.68.2:443:443/tcp"
      - "[2600:1700:2920:1760:aa5e:45ff:fecf:3c47]:443:443/tcp"
      - "8089:8089/tcp"
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
      - /docker/tailscale-certs:/etc/nginx/omv-certs:ro
      - /docker/flame/ts/state/certs:/etc/nginx/flame-certs:ro
      - /docker/freshrss/ts/state/certs:/etc/nginx/freshrss-certs:ro
      - /docker/jellyfin/ts/state/certs:/etc/nginx/jellyfin-certs:ro
      - /docker/jellyseerr/ts/state/certs:/etc/nginx/jellyseerr-certs:ro
      - /docker/brave/ts/state/certs:/etc/nginx/brave-certs:ro
      - /docker/audiobookshelf/ts/state/certs:/etc/nginx/audiobookshelf-certs:ro
      - /docker/ntfy/ts/state/certs:/etc/nginx/ntfy-certs:ro
      - /docker/immich/ts/state/certs:/etc/nginx/immich-certs:ro
      - /docker/vaultwarden/ts/state/certs:/etc/nginx/vaultwarden-certs:ro
      - /docker/privacy/ts/mullvad/state/certs:/etc/nginx/mullvad-certs:ro
      - /docker/privacy/ts/transmission/state/certs:/etc/nginx/transmission-certs:ro
      - /docker/dockge/ts/state/certs:/etc/nginx/dockge-certs:ro
      - /docker/obico/ts/state/certs:/etc/nginx/obico-certs:ro
      - /docker/owncast/ts/state/certs:/etc/nginx/owncast-certs:ro
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /var/cache/nginx
      - /var/run
      - /var/tmp

networks: {}
